Repository Cartographer3D/cartographer-klipper, pull requests merged in 2024-11, with the labels that each got.

#46 Fix: adjusted max retries from 5 to 10
  scanner.py
Labels: bug, fix

#48 fix: CARTOGRAPHER_TOUCH output to display retry attempt numbers
  scanner.py
Labels: bug, fix

#47 fix: fixed threshold scan probing speed
  scanner.py
Labels: bug, fix

#45 fix: rounded long digits to 4 decimals in CARTOGRAPHER_TOUCH
  scanner.py
Labels: bug, fix

#49 fix: syntax error on retries
  scanner.py
Labels: bug, fix

#55 chore: moved various text from output to debugging
  scanner.py
Labels: chore

#52 fix: updated cartographer.py and scanner.py to update current model
  cartographer.py
  scanner.py
Labels: bug, fix

#50 feat: `MOVE` added to `CARTOGRAPHER_TOUCH`
  scanner.py
Labels: feature

#53 fix: when calibrating dont apply any z offset
  scanner.py
Labels: bug, fix

#58 feat: 5.0.2 firmware added - updates i2c to 400k
  firmware/v2-v3/survey/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/Survey_Cartographer_USB_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.0/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.0/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.0/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.0/Survey_Cartographer_USB_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.1/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.1/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.1/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.1/Survey_Cartographer_USB_8kib_offset.bin
Labels: feature, fix

#59 chore: create pull request template
  .github/pull_request_template.md
Labels: chore

#60 revert: firmware 5.0.2 to 5.0.0
  firmware/v2-v3/survey/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/Survey_Cartographer_USB_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.2/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.2/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.2/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.2/Survey_Cartographer_USB_8kib_offset.bin
Labels: bug, fix

#63 Improved Threshold Scan, Touch and other small fixes
  scanner.py
Labels: feature

#67 fix: save speed upon threshold save
  scanner.py
Labels: bug, fix

#70 Feature: add firmware flasher
  firmware.sh
  firmware/v2-v3/combined-firmware/4.0.0/Full_Cartographer_CAN_1M_4_0_1.bin
  firmware/v2-v3/combined-firmware/4.0.0/Full_Cartographer_USB_4_0_0.bin
  firmware/v2-v3/combined-firmware/5.0.0/Full_Survey_Cartographer_CAN_1M_5_0_0.bin
  firmware/v2-v3/combined-firmware/5.0.0/Full_Survey_Cartographer_CrealityK1_USB_5_0_0.bin
  firmware/v2-v3/combined-firmware/5.0.0/Full_Survey_Cartographer_USB_5_0_0.bin
  firmware/v2-v3/survey/5.0.0/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/5.0.0/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/5.0.0/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/5.0.0/Survey_Cartographer_K1_USB_8kib_offset.bin
  firmware/v2-v3/survey/5.0.0/Survey_Cartographer_USB_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.0/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.0/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.0/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.0/Survey_Cartographer_USB_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.1/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.1/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.1/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.1/Survey_Cartographer_USB_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.2/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.2/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.2/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/archive/5.0.2/Survey_Cartographer_USB_8kib_offset.bin
  firmware/v2-v3/survey/archive/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/archive/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/archive/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/archive/Survey_Cartographer_USB_8kib_offset.bin
Labels: feature

#71 feature: TEMPERATURE_WAIT instead of m109
  scanner.py
Labels: feature

#75 fix set temp not increasing temp
  scanner.py
Labels: bug, fix

#76 flasher will now pull from github into /tmp
  firmware.sh
Labels: feature

#78 Fix: stops users setting offet below 0
  scanner.py
Labels: bug, fix

#68 Feature: model mode switching & command update
  scanner.py
Labels: feature

#79 feat: enable ruff and pyright checks
  .DS_Store
  .github/workflows/pull-request.yml
  DEVELOPMENT.md
  __init__.py
  pyproject.toml
  scanner.py
  typings/adxl345.pyi
  typings/bed_mesh.pyi
  typings/chelper.pyi
  typings/clocksync.pyi
  typings/manual_probe.pyi
  typings/mcu.pyi
  typings/msgproto.pyi
  typings/pins.pyi
  typings/probe.pyi
  typings/thermistor.pyi
Labels: feature

#87 Run shfmt on firmware.sh
  firmware.sh
Labels: skip-changelog

#85 Use release drafter to make stable releases
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#88 v1.1.0-beta (FW 5.1.0)
  .DS_Store
  .github/release-drafter.yml
  .github/workflows/pull-request.yml
  .github/workflows/release-drafter.yml
  DEVELOPMENT.md
  __init__.py
  firmware.sh
  pyproject.toml
  scanner.py
  typings/adxl345.pyi
  typings/bed_mesh.pyi
  typings/chelper.pyi
  typings/clocksync.pyi
  typings/manual_probe.pyi
  typings/mcu.pyi
  typings/msgproto.pyi
  typings/pins.pyi
  typings/probe.pyi
  typings/thermistor.pyi
Labels: beta

#90 fix: flashing via usb fixed to not say CAN Flash Success
  firmware.sh
Labels: bug, fix

#83 chore: rewrote lambda as def
  scanner.py
Labels: chore, skip-changelog

#80 Chore: removed random useless code
  scanner.py
Labels: chore, skip-changelog

#96 Use firmware flasher to flash from any branch (#86)
  firmware.sh
Labels: bug, fix

#97 Create helper macro for integration testing
  DEVELOPMENT.md
  cartographer_ci_test.cfg
Labels: skip-changelog

#91 Add: v5.1.0 firmware (k1 missing)
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_USB_8kib_offset.bin
Labels: feature, beta

#100 feat: add k1 USB 5.1.0 firmware
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_K1_USB_8kib_offset.bin
Labels: feature

#101 feat: add k1 USB 5.1.0 firmware (#100)
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_K1_USB_8kib_offset.bin
Labels: feature

#102 Fix: z offset issue
  scanner.py
Labels: bug, fix

#103 fix: z offset bug (#102)
  scanner.py
Labels: bug, fix

#105 fix: z offset bug (#102)
  scanner.py
Labels: bug, fix

#81 Remove PROBE_CALIBRATE and associated helper function
  scanner.py
Labels: feature

#84 Fix: Added error message when calibration encounters error
  scanner.py
Labels: bug, fix

#94 Add types for config, printer and reactor
  scanner.py
  typings/configfile.pyi
  typings/gcode.pyi
  typings/klippy.pyi
  typings/reactor.pyi
Labels: chore

#107 Add 5.1.0 HT firmware
  firmware.sh
  firmware/v2-v3/survey/5.1.0/HT/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/HT/Survey_Cartographer_USB_8kib_offset.bin
Labels: feature, beta

#108 Fix change max_retries float to int
  scanner.py
Labels: bug, fix, beta

#106 Add types for gcode and gcode command
  scanner.py
  typings/configfile.pyi
  typings/gcode.pyi
  typings/klippy.pyi
  typings/reactor.pyi
Labels: skip-changelog

#111 Firmware 5.1.0 ht fix
  firmware/v2-v3/survey/5.1.0/HT/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/HT/Survey_Cartographer_USB_8kib_offset.bin
Labels: bug, fix

#116 remove duplicate line
  scanner.py
Labels: chore, skip-changelog

#118 fix: pin python version to 3.9
  .github/workflows/pull-request.yml
  pyproject.toml
  scanner.py
  typings/mcu.pyi
Labels: bug, skip-changelog

#124 removes graph generation and imports
  scanner.py
Labels: fix, chore, beta

#125 fix: tolerance is not a tuple
  scanner.py
Labels: bug, skip-changelog

#117 Fix PR #110 wait temp error
  scanner.py
Labels: bug, fix

#114 Chore: Removed unused ADXL functions and variables
  scanner.py
Labels: chore

#120 Feature: pass params from calibrate to touch
  scanner.py
  typings/gcode.pyi
Labels: feature

#123 feat: setup ci to check k1 environment
  .github/workflows/pull-request.yml
  ci/k1-requirements.txt
  ci/standard-requirements.txt
  pyproject.toml
  requirements.txt
  scanner.py
Labels: feature

#130 Ensure beta and develop are aligned
  scanner.py
Labels: skip-changelog

#132 Merge pull request #131 into beta
  scanner.py
Labels: skip-changelog

#115 Chore: More code cleanup
  scanner.py
Labels: chore, skip-changelog

#134 chore: make threshold result a dataclass
  scanner.py
Labels: chore, skip-changelog

#135 chore: add types for toolhead
  scanner.py
  typings/gcode.pyi
  typings/heater.pyi
  typings/kinematics/extruder.pyi
  typings/klippy.pyi
  typings/toolhead.pyi
Labels: chore, skip-changelog

#72 Create setup.py to migrate and setup
  scripts/README.md
  scripts/setup.py
Labels: feature
