Repository Cartographer3D/cartographer-klipper, pull requests merged in 2024-12, with the labels that each got.

#139 Add types for modules
  __init__.py
  scanner.py
  typings/axis_twist_compensation.pyi
  typings/bed_mesh.pyi
  typings/clocksync.pyi
  typings/configfile.pyi
  typings/exclude_object.pyi
  typings/gcode.pyi
  typings/gcode_move.pyi
  typings/heaters.pyi
  typings/homing.pyi
  typings/kinematics/extruder.pyi
  typings/kinematics/none.pyi
  typings/klippy.pyi
  typings/manual_probe.pyi
  typings/mcu.pyi
  typings/msgproto.pyi
  typings/pins.pyi
  typings/probe.pyi
  typings/reactor.pyi
  typings/stepper.pyi
  typings/temperature_sensor.pyi
  typings/thermistor.pyi
  typings/toolhead.pyi
  typings/webhooks.pyi
Labels: skip-changelog

#145 Fix fuzzy touch name
  scanner.py
Labels: bug, skip-changelog, beta

#150 fix: fuzzy is not sleepy (#145)
  scanner.py
Labels: bug, skip-changelog

#152 Fix/text bug calibrate
  scanner.py
Labels: bug, fix, skip-changelog

#153 Fix text bug calibrate (#152)
  scanner.py
Labels: bug

#155 chore: fix formatting
  scanner.py
Labels: bug, chore

#147 fix: remove scanner.z_offset
  scanner.py
Labels: bug

#146 feat: use an enum for trigger_method
  scanner.py
Labels: feature

#156 Implement probe get_status
  scanner.py
Labels: feature, beta

#158 Implement probe get_status (#156)
  scanner.py
Labels: skip-changelog

#159 fixed k1 5.1.0 firmware version
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_K1_USB_8kib_offset.bin
Labels: bug, fix, skip-changelog

#160 fixed k1 5.1.0 firmware version (#159)
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_K1_USB_8kib_offset.bin
Labels: bug, fix, skip-changelog, beta

#166 feat: make macros clickable in console
  scanner.py
Labels: feature

#167 feat: check bed leveling before threshold scan
  scanner.py
  typings/klippy.pyi
  typings/quad_gantry_level.pyi
  typings/z_tilt.pyi
Labels: feature

#165 Add model required to threshold_scan
  scanner.py
Labels: bug, beta

#169 Firmware.py V0.0.1
  scripts/README.md
  scripts/firmware.py
Labels: feature, beta

#170 Better mcu identify error
  scanner.py
Labels: bug

#173 Move only once
  scanner.py
Labels: bug, skip-changelog

#174 minor text fixes
  scripts/firmware.py
Labels: bug, skip-changelog

#175 Update beta
  scanner.py
  scripts/firmware.py
Labels: skip-changelog

#178 Release v1.1.0
  .DS_Store
  .github/release-drafter.yml
  .github/workflows/pull-request.yml
  .github/workflows/release-drafter.yml
  DEVELOPMENT.md
  __init__.py
  cartographer_ci_test.cfg
  ci/k1-requirements.txt
  ci/standard-requirements.txt
  firmware.sh
  firmware/v2-v3/survey/5.1.0/HT/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/HT/Survey_Cartographer_USB_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_CAN_1000000_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_CAN_250000_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_CAN_500000_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_K1_USB_8kib_offset.bin
  firmware/v2-v3/survey/5.1.0/Survey_Cartographer_USB_8kib_offset.bin
  pyproject.toml
  requirements.txt
  scanner.py
  scripts/README.md
  scripts/firmware.py
  scripts/setup.py
  typings/adxl345.pyi
  typings/axis_twist_compensation.pyi
  typings/bed_mesh.pyi
  typings/chelper.pyi
  typings/clocksync.pyi
  typings/configfile.pyi
  typings/exclude_object.pyi
  typings/gcode.pyi
  typings/gcode_move.pyi
  typings/heaters.pyi
  typings/homing.pyi
  typings/kinematics/extruder.pyi
  typings/kinematics/none.pyi
  typings/klippy.pyi
  typings/manual_probe.pyi
  typings/mcu.pyi
  typings/msgproto.pyi
  typings/pins.pyi
  typings/probe.pyi
  typings/quad_gantry_level.pyi
  typings/reactor.pyi
  typings/stepper.pyi
  typings/temperature_sensor.pyi
  typings/thermistor.pyi
  typings/toolhead.pyi
  typings/webhooks.pyi
  typings/z_tilt.pyi
Labels: skip-changelog

#183 [FirmwareFlasher] Change text from find to select firmware
  scripts/firmware.py
Labels: chore

#184 [FirmwareFlasher] fix -f arg not starting at that specific menu
  scripts/firmware.py
Labels: fix

#185 [FirmwareFlasher] Move dfu flash to advanced menu
  scripts/firmware.py
Labels: chore

#187 [FirmwareFlasher] Updates Katapult and Checks Origin
  scripts/firmware.py
Labels: feature

#181 [FirmwareFlasher] Remove Obsolete Firmware.sh
  firmware.sh
Labels: chore

#188 Firmwareflasher0.0.2-beta
  firmware.sh
  scripts/firmware.py
Labels: skip-changelog, beta

#189 [Firmware] Add 5.1.0 Combined DFU Firmware
  firmware/v2-v3/combined-firmware/5.1.0/Full_Survey_Cartographer_CAN_1M_5_1_0.bin
  firmware/v2-v3/combined-firmware/5.1.0/Full_Survey_Cartographer_CrealityK1_USB_5_1_0.bin
  firmware/v2-v3/combined-firmware/5.1.0/Full_Survey_Cartographer_USB_5_1_0.bin
Labels: feature

#190 [Firmware] Add DFU Combined Firmware 5.1.0 (#189)
  firmware/v2-v3/combined-firmware/5.1.0/Full_Survey_Cartographer_CAN_1M_5_1_0.bin
  firmware/v2-v3/combined-firmware/5.1.0/Full_Survey_Cartographer_CrealityK1_USB_5_1_0.bin
  firmware/v2-v3/combined-firmware/5.1.0/Full_Survey_Cartographer_USB_5_1_0.bin
Labels: feature

#193 [FirmwareFlasher] Change Menu Calls to Returns
  scripts/firmware.py
Labels: bug, fix

#191 [FirmwareFlasher] Adds logging
  scripts/firmware.py
Labels: feature

#192 [FirmwareFlasher] Query DFU Device Inf Loop + Anykey Exit
  scripts/firmware.py
Labels: feature, fix

#194 [FirmwareFlasher] Adds Configuration file & Edit Menu + Minor Text Changes
  scripts/firmware.cfg
  scripts/firmware.py
Labels: feature

#196 Merge Develop into Beta
  scripts/firmware.cfg
  scripts/firmware.py
Labels: skip-changelog

#197 [FirmwareFlasher] Repository would error when case-sensitive - 0.0.4
  scripts/firmware.py
Labels: fix

#201 [FirmwareFlasher] Normalise GIT repo origin
  .gitignore
  scripts/firmware.py
Labels: skip-changelog

#200 [FirmwareFlasher] Add LSUSB (/dev/ Directory to Config Options
  scripts/firmware.py
Labels: skip-changelog

#198 [FirmwareFlasher] Adds Advanced Menu for All Firmware
  scripts/firmware.py
Labels: feature

#204 Develop2beta
  .gitignore
  scanner.py
  scripts/firmware.py
Labels: skip-changelog

#206 [FirmwareFlasher] Fixes klippy env path
  scripts/firmware.py
Labels: fix, skip-changelog

#208 [FirmwareFlasher] fixes klippy env path (#206)
  scripts/firmware.py
Labels: fix, skip-changelog
